// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "tgservice/internal/model"
)

// MessageUsecase is an autogenerated mock type for the MessageUsecase type
type MessageUsecase struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: ctx, sessionID, peer, text
func (_m *MessageUsecase) SendMessage(ctx context.Context, sessionID string, peer string, text string) (int64, error) {
	ret := _m.Called(ctx, sessionID, peer, text)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return rf(ctx, sessionID, peer, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = rf(ctx, sessionID, peer, text)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, sessionID, peer, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeMessages provides a mock function with given fields: ctx, sessionID
func (_m *MessageUsecase) SubscribeMessages(ctx context.Context, sessionID string) (<-chan model.MessageDTO, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeMessages")
	}

	var r0 <-chan model.MessageDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan model.MessageDTO, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan model.MessageDTO); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.MessageDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMessageUsecase creates a new instance of MessageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageUsecase {
	mock := &MessageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
