// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "tgservice/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TelegramMessenger is an autogenerated mock type for the TelegramMessenger type
type TelegramMessenger struct {
	mock.Mock
}

// Messages provides a mock function with given fields: ctx, clientID
func (_m *TelegramMessenger) Messages(ctx context.Context, clientID string) (<-chan model.MessageDTO, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 <-chan model.MessageDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan model.MessageDTO, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan model.MessageDTO); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.MessageDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Send provides a mock function with given fields: ctx, clientID, peer, text
func (_m *TelegramMessenger) Send(ctx context.Context, clientID string, peer string, text string) (int64, error) {
	ret := _m.Called(ctx, clientID, peer, text)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return rf(ctx, clientID, peer, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = rf(ctx, clientID, peer, text)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, clientID, peer, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTelegramMessenger creates a new instance of TelegramMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramMessenger {
	mock := &TelegramMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
